---
title: "Cell Counts"
author: "EL Strand"
date: "5/24/2021"
output: html_document
---

Code modified from R. Cunning, H. Putnam, and E5 group; link [here](https://github.com/urol-e5/timeseries/blob/master/timepoint_1/scripts/Sym-Density.Rmd).

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load packages.
```{r}
rm(list=ls())

library(plyr)
library(dplyr)
library(tidyverse)
library(ggpubr)
library(purrr)
```

# Holobiont Integration sample processing 

Loading data frames 

```{r}
# Surface area data
sa <- read.csv("Physiology_variables/Respirometry/coral_surface_area.csv") %>% dplyr::rename(Plug_ID = Sample_ID) %>% select(Plug_ID, surface.area.cm2)
sa$Plug_ID <- as.character(sa$Plug_ID)

# Tissue homogenate volume data
homog_vols <- read_csv("Physiology_variables/homogenate_vol.csv") %>% select(Species, Plug_ID, vol_mL)
homog_vols$Plug_ID <- as.character(homog_vols$Plug_ID)

# Coral sample metadata
metadata <- read_csv("Environmental_data/Master_Fragment.csv") %>% select(Species, Plug_ID, Tank, Treatment, Temperature, CO2, Timepoint, ANALYSIS, Sample.Date) %>%
  subset(ANALYSIS=="Physiology" | ANALYSIS=="Physiology/Molecular")
metadata$Plug_ID <- as.character(metadata$Plug_ID)

# Join homogenate volumes and surface area with sample metadata
metadata <- full_join(metadata, homog_vols) %>% full_join(sa) %>% filter(!is.na(vol_mL)) %>% 
  filter(!is.na(ANALYSIS))
```

# Testing the cellometer

Import dataframes.
```{r}
# Haemocytometer count data
haemo.raw <- read_csv("Physiology_variables/cell-counts/cell-counts-testing-haemo.csv") %>% filter(!is.na(Plug_ID))
  haemo.raw$Plug_ID <- as.character(haemo.raw$Plug_ID)
cellometer.raw <- read_csv("Physiology_variables/cell-counts/cell-counts-testing-cellometer.csv")
  cellometer.raw$Plug_ID <- as.character(cellometer.raw$Plug_ID)

# Adding in Porites test data
past <- read_csv("Physiology_variables/cell-counts/Porites-test.csv") %>% select(Vial, Species, homo.vol, Surface.Area) %>%
  dplyr::rename(Plug_ID = Vial) %>% dplyr::rename(vol_mL = homo.vol) %>% dplyr::rename(surface.area.cm2 = Surface.Area)
past$Plug_ID <- as.character(past$Plug_ID)
past$period <- "Post-homogenizing"
```

Calculate mean counts.
```{r}
## Haemocytometer 
# Calculate mean counts for each sample
haemo <- haemo.raw %>%
  select(Plug_ID, Squares_Counted, matches("Count[0-9]"), Tech) %>%
  gather("rep", "count", -Plug_ID, -Squares_Counted, -Tech) %>%
  dplyr::group_by(Plug_ID, Squares_Counted) %>%
  mutate(count.mean = mean(count))

# Join mean counts with sample metadata
haemo <- full_join(haemo, metadata) 

# Normalize counts by homogenat volume and surface area
haemo <- haemo %>%
  mutate(cells.mL = count.mean * 10000 / Squares_Counted,
         cells = cells.mL * vol_mL,
         haemo.cells.cm2 = cells / surface.area.cm2)

haemo <- haemo %>% filter(!is.na(haemo.cells.cm2))
haemo$Timepoint <- factor(haemo$Timepoint, levels=c("Day 1","Day 2","1 week","2 week","4 week","6 week","8 week","12 week","16 week"))

## Cellometer
cellometer <- cellometer.raw %>% 
  select(Date, Period, Plug_ID, matches("Cell_mL[0-3]")) %>%
  gather("rep", "count", -Period, -Plug_ID, -Date) %>% filter(!is.na(count)) %>%
  dplyr::group_by(Plug_ID, Period) %>%
  mutate(count.mean = mean(count)) %>%
  ungroup(Period)

cellometer <-full_join(cellometer, metadata)

cellometer <- cellometer %>%
  mutate(cells.mL = count.mean,
         cells = cells.mL * vol_mL,
         cellometer.cells.cm2 = cells / surface.area.cm2)

cellometer <- cellometer %>% filter(!is.na(cellometer.cells.cm2))
cellometer$Timepoint <- factor(cellometer$Timepoint, levels=c("Day 1","Day 2","1 week","2 week","4 week","6 week","8 week","12 week","16 week"))
```

Creating large dataframe.
```{r}
counts <- full_join(cellometer, haemo, join_by = "Plug_ID") %>% 
  filter(!is.na(count.mean)) %>% 
  select(-rep, -count, -count.mean, -cells.mL, -cells, -Squares_Counted) %>%
  summarise_each(funs(first(na.omit(.)))) # combining rows that have the same data (plug ids with cellometer and haemcy but originally on two different rows)

write_csv(path = "Physiology_variables/cell-counts/calculated-cell-counts.csv", counts)
```

Creating model.
```{r}
lm <- counts %>% subset(Period == "Pre-homogenizing" | Period == "Post-homogenizing") %>%
  group_by(Species, Period) %>%
  nest() %>% # nest to do this for each group (Species, Period) defined above 
  mutate(Mod = map(data, ~lm(cellometer.cells.cm2 ~ haemo.cells.cm2, data = .x))) %>% # Fit linear model
  mutate(R2 = map_dbl(Mod, ~round(summary(.x)$r.squared, 3))) %>%   # Get the R2
  unnest(cols = c(data)) # unnest to plot below 

c1c2.lm <- cellometer.raw %>% subset(Period == "Pre-homogenizing" | Period == "Post-homogenizing") %>%
  group_by(Period) %>%
  nest() %>% # nest to do this for each group (Species, Period) defined above 
  mutate(Mod = map(data, ~lm(Cell_mL1 ~ Cell_mL2, data = .x))) %>% # Fit linear model
  mutate(R2 = map_dbl(Mod, ~round(summary(.x)$r.squared, 3))) %>%   # Get the R2
  unnest(cols = c(data)) # unnest to plot below
```

Plotting
```{r}
cols <- c("lightblue", "blue", "pink", "red")

haemo %>% na.omit() %>%
  ggplot(aes(x = Timepoint, y = haemo.cells.cm2, group = Treatment, color = Treatment)) +
  scale_color_manual(values = cols) +
  theme_classic() + 
  facet_grid(~Species) + 
  theme(axis.text.x = element_text(angle = 60, vjust = 1.2, hjust = 1.3)) + #Set the text angle
  labs(x = "",y = "Cell Density (Cells/cm2)") +
  geom_jitter(width = 0.1) +  
  stat_summary(fun.data = mean_cl_normal, fun.args = list(mult = 1),    # Plot standard error
               geom = "errorbar", color = "black", width = 0.1) +
  stat_summary(fun = mean, geom = "point", color = "black")           # Plot mean

testing <- counts %>% subset(Period == "Pre-homogenizing" | Period == "Post-homogenizing") %>%
  ggplot(aes(x=cellometer.cells.cm2, y=haemo.cells.cm2, group = Period, color = Period)) + 
  geom_jitter(width = 0.1) + 
  facet_grid(Species ~ Period) +
  labs(color='Period') +
  theme_classic() + 
  ylim(0, 3500000) + 
  xlim(0, 3500000) +
  geom_abline(slope=1) +
  geom_label(data = lm, 
             aes(x = Inf, y = Inf, 
                 label = paste("R2 = ", R2, sep = " ")),
             hjust = 1, vjust = 1); testing

c1c2 <- cellometer.raw %>% subset(Period == "Pre-homogenizing" | Period == "Post-homogenizing") %>%
  ggplot(aes(x=Cell_mL1, y=Cell_mL2, group = Period, color = Period)) + 
  geom_jitter(width = 0.1) + 
  facet_grid(~Period) +
  labs(color='Period') + 
  theme_classic() +
  ylim(0, 1500000) + 
  xlim(0, 1500000) + 
  geom_abline(slope=1) + 
  geom_label(data = c1c2.lm, 
             aes(x = Inf, y = Inf, 
                 label = paste("R2 = ", R2, sep = " ")),
             hjust = 1, vjust = 1); c1c2
  
ggsave(file="Output/Cellometer-testing.png", testing, width = 11, height = 6, units = c("in"))
ggsave(file="Physiology_variables/cell-counts/Cellometer-c1c2.png", c1c2, width = 11, height = 6, units = c("in"))
```

