---
title: "ITS2 analysis"
author: "HM Putnam"
date: "2/14/2020"
output: html_document
---

Clear workspace. 
```{r}
rm(list=ls()) 
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

## install packages if you dont already have them
if (!require("tidyverse")) install.packages("tidyverse")
if (!require("lubridate")) install.packages("lubridate")
if (!require("vegan")) install.packages("vegan")
if (!require("ggfortify")) install.packages("ggfortify")

# load packages
library(tidyverse)
library(lubridate)
library(vegan)
library(ggfortify)

```

Sample 192 and 193 were switched in 'ITS2 Profiles' csv. 

```{r}
#read in ITS2 profile counts data generated by SymPortal
data <- read.csv("ITS2_seq/R_Input/ITS2_Profiles.csv", sep=",", header=TRUE)
rownames(data) <-data$sample_name 
otumat <- as.matrix(data[,-c(1)])
#otumat <- as.matrix(t(otumat))

#read in sample metadata
meta <- read.csv("Environmental_data/Master_Fragment.csv", header=T, sep=",", na.string="NA") %>% select(Plug_ID, Species, Timepoint, Temperature, Treatment, CO2)
meta$Plug_ID <- as.character(meta$Plug_ID)

filter(meta, Plug_ID == "2153") #2153 was used for physiology and molecular so change master spreadsheet to say 12 hour not Day 1
meta$Timepoint[which(meta$Plug_ID == "2153")] <- "12 hour"

filter(meta, Timepoint == "0 hour" & Treatment == "HTAC" & Species == "Mcapitata")

samples <- read.csv("ITS2_seq/R_Input/Sample_variables.csv") %>% select(Plug_ID, sample) %>% dplyr::rename(sample_name = sample)
samples$Plug_ID <- as.character(samples$Plug_ID)

meta <- full_join(meta, samples, by = "Plug_ID") %>% na.omit()
```

```{r}
#Pacuta
Pact <- merge(data, meta, by="sample_name") # combine meta and ITS2 type profile data
Pact <- subset(Pact, Species == "Pacuta") # subset to only Pacuta 
Pact_meta <- Pact[,14:19] # select 
str(Pact_meta)
Pact_meta$Timepoint <- as.factor(Pact_meta$Timepoint)
rownames(Pact) <- Pact$sample_name
Pact <- as.matrix(Pact[,2:13])

Rel.Sym.Data <- Pact/rowSums(Pact) #calculate the Relative Abundance
N <- rowSums(Rel.Sym.Data) # calculate row sums of the relative abundnaces, should sum to 1
N #Display Row Sums, should all be 1

#Transform Relative Abundance Matrix using sqrt
Trans.Rel.Sym.Data <- sqrt(Rel.Sym.Data) #sqrt transform the matrix
Trans.Rel.Sym.Data #view data

##### PCA #####

sym.pca.res <- prcomp(Trans.Rel.Sym.Data, retx=TRUE) #principal components analysis on sym data
summary(sym.pca.res) #analysis summary

#use scree diagram to determine break in majority versus minority variation explaination components
screeplot(sym.pca.res, type="lines")

#plot the PCA
autoplot(sym.pca.res)
autoplot(sym.pca.res, data = Pact_meta, colour = 'Timepoint', shape='Treatment')
```

```{r}
#Mcap
Mcap <- merge(data, meta, by="sample_name")
Mcap <- subset(Mcap, Species == "Mcapitata")
Mcap_meta <- Mcap[,14:19]
str(Mcap_meta)
Mcap_meta$Timepoint <- as.factor(Mcap_meta$Timepoint)
rownames(Mcap) <- Mcap$sample_name
Mcap <- as.matrix(Mcap[,2:13])

Rel.Sym.Data <- Mcap/rowSums(Mcap) #calculate the Relative Abundance
N <- rowSums(Rel.Sym.Data) # calculate row sums of the relative abundnaces, should sum to 1
N #Display Row Sums, should all be 1

#Transform Relative Abundance Matrix using sqrt
Trans.Rel.Sym.Data <- sqrt(Rel.Sym.Data) #sqrt transform the matrix
Trans.Rel.Sym.Data #view data

##### PCA #####

sym.pca.res <- prcomp(Trans.Rel.Sym.Data, retx=TRUE) #principal components analysis on sym data
summary(sym.pca.res) #analysis summary
plot(sym.pca.res)

#use scree diagram to determine break in majority versus minority variation explaination components
screeplot(sym.pca.res, type="lines")

#plot the PCA
autoplot(sym.pca.res)
autoplot(sym.pca.res, data = Mcap_meta, colour = 'Treatment', shape='Timepoint')
```

```{r}
#All Data
Rel.data <- data[,2:13]/rowSums(data[,2:13]) ## exclude the first column bc it is not an integer 
Rel.data$sample_name <- rownames(Rel.data)
all.data <- merge(Rel.data, meta, by="sample_name")
all.data <- all.data[,-1]

Profile <- colnames(all.data[,1:12])
Profile 

df <- all.data %>% dplyr::group_by(Timepoint, Species, Treatment) %>% mutate(id = row_number()) %>%
  pivot_longer(cols = C1d.C42.2.C1.C3cg:D1.D4.D6.D1ab,
               names_to = c("Profile"),
               values_to="rel.abun")

df$Timepoint <- factor(df$Timepoint, levels=c("0 hour","6 hour","12 hour","30 hour","1 week","2 week","4 week", "6 week", "8 week", "12 week", "16 week"))

df$Group <- paste(df$Timepoint, df$id, sep="_")
df$Group <- as.factor(df$Group)

df$Group <- factor(df$Group, levels=c("0 hour_1", "0 hour_2", "0 hour_3",
                                      "6 hour_1", "6 hour_2", "6 hour_3",
                                      "12 hour_1", "12 hour_2", "12 hour_3", "12 hour_4",
                                      "30 hour_1", "30 hour_2", "30 hour_3",
                                      "1 week_1", "1 week_2", "1 week_3",
                                      "2 week_1", "2 week_2", "2 week_3",
                                      "4 week_1", "4 week_2", "4 week_3", 
                                      "6 week_1", "6 week_2", "6 week_3", 
                                      "8 week_1", "8 week_2", "8 week_3", 
                                      "12 week_1", "12 week_2", "12 week_3", 
                                      "16 week_1", "16 week_2", "16 week_3"))

str(df)

ggplot(data = df, mapping = aes(x = Group, y = rel.abun, fill = Profile)) +
    geom_bar(position="fill", stat="identity") +
    facet_wrap(facets =  vars(Species, Treatment), ncol = 4)+
    ylab("Relative Abundance")+
    theme_classic()+
    theme(axis.text.x = element_text(size=rel(0.3),angle = 90))+
    guides(shape = guide_legend(override.aes = list(size = 0.2)))+
    guides(color = guide_legend(override.aes = list(size = 0.2)))+
    theme(legend.title = element_text(size = 6), 
               legend.text = element_text(size = 4))

ggsave("Output/Final_Figures/rel.abund.its2.pdf")
ggsave("Output/Final_Figures/rel.abund.its2.png")

```

Bubble plot.

Profiles (colors listed in this reverse order

```{r}
colours = c("violetred4",  "violetred3", "violetred2", "violetred1", "palevioletred1", "lightpink1", "lightsalmon", "sienna1", "tomato",
"orangered","orangered3", "forestgreen")

its2.bubble.plot = 
  ggplot(df, aes(x = Timepoint, y = Profile)) + 
  geom_point(aes(size = rel.abun, fill = Profile), alpha = 0.75, shape = 21) + 
  scale_size_continuous(limits = c(0.000001, 100), range = c(1,17), breaks = c(1,25,50,100)) + 
  facet_wrap(facets =  vars(Species, Treatment), ncol = 4) + 
  theme(strip.background = element_rect(color="black", fill="white", size=1.5, linetype="solid")) +
  labs(x = "", y = "", size = "Relative Abundance (%)", fill = "")  + 
  theme(legend.key=element_blank(), 
  axis.text.x = element_text(colour = "black", size = 12, angle = 90, vjust = 0.3, hjust = 1), 
  axis.text.y = element_text(colour = "black", size = 11), 
  legend.text = element_text(size = 10, face ="bold", colour ="black"), 
  legend.title = element_text(size = 12, face = "bold"), 
  panel.background = element_blank(), panel.border = element_rect(colour = "black", fill = NA, size = 1.2), 
  legend.position = "top") +  
  scale_fill_manual(values = colours, guide = FALSE) + 
  ggtitle("All individuals projected n=3") + 
  scale_y_discrete(limits = rev(levels(df$Profile))) 

its2.bubble.plot

ggsave("Output/Final_Figures/rel.abund.its2.bubble.pdf", width = 11, height = 8, units = c("in"))

```



```{r}
## PERMANOVA
#MCAP
Mcap <- all.data %>%
  filter(Species == "Mcapitata")

MC.mat <- Mcap[,1:12]
MC.info <- Mcap[,13:18] 
MC.info %>% group_by(Treatment, Timepoint) %>% count("Rep") # checking sample sizes; should all be 3

MC.permanova <- adonis(MC.mat ~ Temperature*CO2*Timepoint, data=MC.info, method = "bray", permutations=999)
MC.permanova


Pact <- all.data %>%
  filter(Species == "Pacuta")

PA.mat <- Pact[,1:12]
PA.info <- Pact[,13:18]
PA.info %>% group_by(Treatment, Timepoint) %>% count("Rep") # checking sample sizes; should all be 3 except for TP11 HTHC

PA.permanova <- adonis(PA.mat ~ Temperature*CO2*Timepoint, data=PA.info, method = "bray", permutations=999)
PA.permanova

```


# Subset to 5 TP for CSP paper 

30 hour, 2 wk, 6 wk, 8 wk, 12 wk

```{r}
tp5 <- df %>% subset(Timepoint == "30 hour" | Timepoint == "2 week" | Timepoint == "6 week" | Timepoint == "8 week" | Timepoint == "12 week")

ggplot(data = tp5, mapping = aes(x = Group, y = rel.abun, fill = Profile)) +
    geom_bar(position="fill", stat="identity") +
    facet_wrap(facets =  vars(Species, Treatment), ncol = 4) +
    ylab("Relative Abundance (%)") +
    xlab("Timepoint_Replicate") +
    theme_classic() +
    theme(axis.text.x = element_text(size=rel(0.3),angle = 90)) +
    guides(shape = guide_legend(override.aes = list(size = 0.2))) +
    guides(color = guide_legend(override.aes = list(size = 0.2))) +
    theme(legend.title = element_text(size = 6), 
               legend.text = element_text(size = 4)) +
    

ggsave("Output/Final_Figures/CSP-rel.abund.its2.pdf")
ggsave("Output/Final_Figures/CSP-rel.abund.its2.png")
```

