---
title: "Physiological_variability"
author: "EL Strand"
date: "7/19/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE, message = FALSE)

library(data.table)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(stats)
```

Reading in data and calculating MAD
```{r}
## Bleaching Score
Bleaching_score_data <- read.csv("Physiology_variables/Bleaching_Score/Bleaching_Score.csv", header=T, sep=",", na.string="NA") 
Bleaching_score_data$Group <- as.character(Bleaching_score_data$Group)
Bleaching_score_data$PLUG.ID <- as.character(Bleaching_score_data$PLUG.ID)
str(Bleaching_score_data)

 MADS <- Bleaching_score_data %>% 
      group_by(Species, Timepoint, Treatment) %>%
      summarize(MADev = mad(Bleaching.Score, center = median(Bleaching.Score), constant = 1.4826, na.rm = TRUE))
 
MADS$SpGroup <- paste0(MADS$Species, MADS$Treatment)
 
```
 
Plotting MAD through Time
```{r}

cols <- c("lightblue", "blue", "salmon", "red3")

MADS$Timepoint <- factor(MADS$Timepoint, levels = c("Week1", "Week2", "Week3", "Week4", "Week5", "Week6", "Week7", "Week8", "Week9", "Week10", "Week11", "Week12", "Week13", "Week14", "Week15", "Week16"))

Fig.All <- ggplot(MADS, aes(x=Timepoint, y=MADev, group=SpGroup)) + 
  geom_line(aes(linetype= Species, colour=Treatment, group=SpGroup), position = position_dodge(width = 0.1), alpha=0.5) + # colour, group both depend on cond2
  geom_point(aes(colour=Treatment, shape=Species), size = 1, position = position_dodge(width = 0.1)) +
  scale_colour_manual(values=cols) +
  #annotate("text", x=43, y=1.85, label = "a", size = 3) + #add text to the graphic for posthoc letters
  #annotate("text", x=132, y=2.15, label = "b", size = 3) + #add text to the graphic for posthoc letters
  #annotate("text", x=c(43,43), y=c(2.45,2.2), label = "ab", size = 3) + #add text to the graphic for posthoc letters
  #annotate("text", x=c(141,141), y=c(3.15,3.4), label = "c", size = 3) + #add text to the graphic for posthoc letters
  #annotate("text", x=35, y=0.5, label = ".", size = 1) + #add text to the graphic for posthoc letters
  xlab("Timepoint") +
  ylab(expression(paste("MAD Color Score"))) +
  theme_bw() + #Set the background color
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1), #Set the text angle
        axis.line = element_line(color = 'black'), #Set the axes color
        panel.border = element_blank(), #Set the border
        panel.grid.major = element_blank(), #Set the major gridlines
        panel.grid.minor = element_blank(), #Set the minor gridlines
        plot.background=element_blank(),  #Set the plot background
        legend.position= "right") + #remove legend background
  ggtitle("A") +
  theme(plot.title = element_text(face = 'bold', 
                                  size = 10, 
                                  hjust = 0))
Fig.All
 

```

