---
title: "Protein-kit-test"
author: "EL Strand"
date: "3/4/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Clears workspace. 
```{r}
rm(list=ls())
```

Load libraries. 
```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(purrr)
library(Rmisc)
```

Load dataframes.
```{r}
protein <- read.csv("Output/soluble_protein.csv")
  protein$Plug_ID <- as.character(protein$Plug_ID)

raw.data <- read.csv("Physiology_variables/Soluble_Protein/20210304_plate1_SP.csv")
  raw.data$X562 <- as.numeric(raw.data$X562)
platemap <- read.csv("Physiology_variables/Soluble_Protein/20210304_platemap1.csv")

data <- full_join(raw.data, platemap, by = "Well") %>% na.omit()
standards <- data %>% filter(grepl("Standard", Plug_ID)) %>% dplyr::rename(Standard = Plug_ID)
```

Plotting standards. 
```{r}
st.name <- c("StandardA", "StandardB", "StandardC", "StandardD", "StandardE", "StandardF", "StandardG", "StandardH", "StandardI")
concentration <- c("2000", "1500", "1000", "750", "500", "250", "125", "25", "0")

standards <- standards %>%
  dplyr::group_by(Standard) %>%
  dplyr::summarise(X562 = mean(X562)) %>%
  mutate(X562.adj = X562 - X562[Standard == "StandardI"])

standards$BSA_ug.mL <- concentration[match(standards$Standard, st.name)]
  standards$BSA_ug.mL <- as.numeric(standards$BSA_ug.mL)
  
nlm <- lm(BSA_ug.mL ~ X562.adj, data = standards)
summary(nlm)

st.plot <- standards %>%
  ggplot(aes(x = X562.adj, y = BSA_ug.mL)) +
  geom_point(color = "blue", size = 1.5) + 
  theme_bw() + 
  geom_smooth(method = "lm") + 
  labs(title = paste("Adj R2 = ", signif(summary(nlm)$adj.r.squared, 5),
                     "; Soluble Protein Standard Curve Pierca BCA Purple Kit")); st.plot
```

Calculating protein based on standard curve. 
```{r}
data <- data %>% 
  dplyr::group_by(Plug_ID) %>%
  summarise(X562 = mean(X562)) %>% 
  mutate(X562.adj = X562 - standards$X562[standards$Standard == "StandardI"],  
         prot_ug.mL.562 = map_dbl(X562.adj, ~ predict(nlm, newdata = data.frame(X562.adj = .))))

st.plot + 
  geom_point(data = data, aes(x = X562.adj, y = prot_ug.mL.562), pch = "X", cex = 5, alpha = 0.3) +
  labs(title = "March 3 2021 - Purple Kit Values")
```

Normalize to SA.
```{r}
purple <- left_join(data, protein, by = "Plug_ID") %>%
  mutate(prot_ug.562 = prot_ug.mL.562 * vol_mL,
         prot_ug.cm2.562 = prot_ug.562 / surface.area.cm2,
         prot_mg.cm2.562 = prot_ug.cm2.562/1000) %>%
  gather(Measurement, Value, 17,20) %>%
  na.omit()
```

Graphing Gold vs. Purple Kit 
```{r}
cols <- c("lightblue", "blue", "pink", "red")
species.names <- list(
  'prot_mg.cm2'="Rapid Gold (new)",
  'prot_mg.cm2.562'="Purple Kit (old)")

species_labeller <- function(variable,value){
  return(species.names[value])}

ggplot(purple, aes(x=Timepoint, y=Value, color=Treatment)) + 
  geom_point() + 
  scale_color_manual(values = cols) +
  ylab("mg.cm2") +
  ggtitle("All points") +
  facet_grid(~Measurement, labeller = species_labeller) +
  theme_classic()

ggplot(purple, aes(x=Timepoint, y=Value, color=Treatment)) + geom_boxplot() +
  scale_color_manual(values = cols) +
  ylab("mg.cm2") +
  facet_grid(~Measurement, labeller = species_labeller) +
  theme_classic()

ggplot(purple, aes(x=Plug_ID, y=Value, color=Measurement)) + 
  geom_point() + 
  geom_line() +
  ylab("mg.cm2") +
  theme_classic()

ggplot(purple, aes(x=prot_ug.cm2.562, y=prot_ug.cm2, color=Treatment)) + geom_point() +
  xlim(0,1300) + ylim(0,1300) + 
  scale_color_manual(values = cols) + theme_bw()

cor.test(purple$prot_ug.cm2.562, purple$prot_ug.cm2)
```

