---
title: "Sample_completeness"
author: "EL Strand"
date: "8/9/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Clears workspace. 
```{r}
rm(list=ls())
```

Loading required libraries. 
```{r}
if (!require("plyr")) install.packages("plyr")
if (!require("dplyr")) install.packages("dplyr")

library(plyr)
library(dplyr)
```

Reading in the output files from physiological assays. 
```{r}
AFDW <- read.csv("Output/Tissue_Biomass.csv") %>% select(Plug_ID, partner, AFDW.mg.cm2)
Chl <- read.csv("Output/chlorophyll.csv") %>% select(Plug_ID, chla.ug.cm2, chlc2.ug.cm2)
TAC <- read.csv("Output/antioxidant_capacity.csv") %>% select(Plug_ID, CRE.umol.mgprot)
SP <- read.csv("Output/soluble_protein.csv") %>% select(Plug_ID, prot_ug.cm2)
Homog_vol <- read.csv("Physiology_variables/homogenate_vol.csv") %>% select(Plug_ID, vol_mL)
Master <- read.csv("Environmental_data/Master_Fragment.csv") %>%
  filter(!ANALYSIS == "Molecular") %>% filter(!ANALYSIS == "Bleaching") %>% filter(!ANALYSIS == "NA") %>% 
  filter(!ANALYSIS == "Molecular Melted") %>% filter(!ANALYSIS == "Molecular BB") %>% # need to keep "Physiology" and "Physiology/Molecular"
  select(Plug_ID, ANALYSIS, Timepoint, Treatment)

# Filtering out the currently missing corals (16). 
Missing.list <- c("2008", "2512", "2522", "2523", "2752", "2880", "2976", "3003", "1603", "1739", "2200", "2528", "2740", "2859", "2981", "2984")
Missing.list <- as.list(Missing.list)
Master <- Master[!grepl(paste(Missing.list, collapse = "|"), Master$Plug_ID),]

Resp <- read.csv("Physiology_variables/Respirometry/Output/Respiration.rates.csv") %>%
  select(Fragment.ID.x, umol.L.sec) %>% dplyr::rename(Plug_ID = Fragment.ID.x) %>% dplyr::rename(Resp_value = umol.L.sec)
  Resp$Plug_ID <- gsub("P-", "", Resp$Plug_ID)
  Resp$Plug_ID <- gsub("M-", "", Resp$Plug_ID)
  Resp <- Resp %>% separate(Plug_ID, c("Plug_ID", "Date")) %>% select(-Date)
  
Photo <- read.csv("Physiology_variables/Respirometry/Output/Photosynthesis.rates.csv") %>%
  select(Fragment.ID.x, umol.L.sec) %>% dplyr::rename(Plug_ID = Fragment.ID.x) %>% dplyr::rename(Photo_value = umol.L.sec)
  Photo$Plug_ID <- gsub("P-", "", Photo$Plug_ID)
  Photo$Plug_ID <- gsub("M-", "", Photo$Plug_ID)
  Photo <- Photo %>% separate(Plug_ID, c("Plug_ID", "Date")) %>% select(-Date)
  
# add in cell counts later

Physiology <- join_all(list(Master, AFDW, Chl, TAC, SP, Homog_vol, Resp, Photo), by='Plug_ID', type='left')
Physiology

Physiology %>%
  write_csv(path = "Output/physiological_assays.csv")
```

List of missing corals from each assay. 
```{r}
AFDW.missing <- Physiology %>% select(Plug_ID, partner, AFDW.mg.cm2) %>% filter(AFDW.mg.cm2 < 0)

Missing_values <- Physiology %>% filter(is.na(Physiology))
  
```


List samples that do not have a chlorophyll value. 
```{r}
Chl_IDs <- Chl %>% select(Plug_ID)
Master_IDs <- Master %>% select(Plug_ID)
Homog_vol

# rows that appear in Chl datasheet but not in Master
  ## dplyr::setdiff(y, z)  : rows that appear in y but not in z
# output is the corals that have a chlorophyll data point but were not in master spreadsheet
Chl_mismatched <- setdiff(Chl_IDs, Master_IDs) 
Chl_mismatched

Chl_mismatched2 <- setdiff(Master_IDs, Chl_IDs) 
Chl_mismatched2



```



