---
title: "Variability"
author: "EL Strand"
date: "2/25/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Clear workspace. 
```{r}
rm(list=ls()) 
```

Read in libraries. 
```{r}
library(ggplot2); library(gridExtra)
library(plyr)
library(dplyr)
library(stats)
library(tidyr)
```


Read in dataframes. Run "Statistics.Rmd" script first to create the physiology results dataframe. 
```{r}
phys <- read.csv("Output/results_physiology.csv")
color <- read.csv("Output/results_colorscore.csv")
growth <- read.csv("Output/results_growth.csv")

cols <- c("lightblue", "blue", "salmon", "red3")
```

Viewing distributions of variables. 
```{r}
hist(color$Bleaching.Score) #not normal; heavily negatively skewed
hist(phys$Pnet_umol.cm2.hr); hist(phys$Pgross_umol.cm2.hr); hist(phys$Rdark_umol.cm2.hr)
hist(phys$Host_AFDW.mg.cm2); hist(phys$Sym_AFDW.mg.cm2); hist(phys$Ratio_AFDW.mg.cm2)
hist(phys$chlc2.ug.cm2)
hist(phys$prot_mg.cm2); hist(phys$cre.umol.mgprot)
```

Calculating MAD (Median Absolute Deviation).
1.4826 constant value is used for normal distributions -- come back to color score and growth for this one.  

```{r}
## Physiology 
phys.mad <- phys %>% select(-chla.ug.cm2) %>% gather("Response", "Response.Value", 10:18) %>%
  group_by(Species, Treatment, Timepoint, Response) %>%
  mutate(mad = mad(Response.Value, center = median(Response.Value), constant = 1.4826, na.rm = FALSE, low = FALSE, high = FALSE)) %>%
  mutate(cv = ((mad/mean(Response.Value))*100)) %>% filter(cv<200) %>% 
  #gather("Measurement", "Value", 13:14) %>%
  mutate(Species = case_when(
    Species == "Mcapitata" ~ "Montipora capitata",
    Species == "Pacuta" ~ "Pocillopora acuta"
  ))
  
phys.mad$Timepoint <- factor(phys.mad$Timepoint, levels=c("Day 1","Day 2","1 week","2 week","4 week","6 week","8 week", "12 week", "16 week"))
ggplot(phys.mad, aes(x=Treatment, y=mad, color=Treatment)) + geom_boxplot() + facet_grid(Species ~ Response) + theme_bw()


## Color Score 
color.mad <- color %>% group_by(Species, Treatment, Blch.Time) %>%
  mutate(mad = mad(Bleaching.Score, center = median(Bleaching.Score), constant = 1.4826, na.rm = FALSE, low = FALSE, high = FALSE)) %>%
  mutate(cv = ((mad/mean(Bleaching.Score))*100)) %>%
  mutate(Species = case_when(
    Species == "Mcapitata" ~ "Montipora capitata",
    Species == "Pacuta" ~ "Pocillopora acuta"
  ))

color.mad$Timepoint <- factor(color.mad$Timepoint, levels = c("Week1", "Week2", "Week3", "Week4", "Week5", "Week6", "Week7", "Week8", "Week9", "Week10", "Week11", "Week12", "Week13", "Week14", "Week15", "Week16"))

## Growth 
growth.mad <- growth %>% group_by(Species, Treatment, Growth.Time) %>%
  mutate(mad = mad(Growth.Rate, center = median(Growth.Rate), constant = 1.4826, na.rm = FALSE, low = FALSE, high = FALSE)) %>%
  mutate(cv = ((mad/mean(Growth.Rate))*100)) %>%
  mutate(Species = case_when(
    Species == "Mcapitata" ~ "Montipora capitata",
    Species == "Pacuta" ~ "Pocillopora acuta"
  ))

growth.mad$Timepoint <- factor(growth.mad$Timepoint, levels = c("Week1", "Week2", "Week4", "Week6", "Week8", "Week10", "Week12", "Week14", "Week16"))
```

Plot CV 
```{r}
total.CV <- ggplot(phys.mad, aes(x=Timepoint, y = cv, group = Treatment, color = Treatment)) +
  geom_line() + geom_point() +
  facet_grid(Species ~ Response) +
  scale_color_manual(values = cols) + 
  xlab("Timepoint") + ylab("Coefficient of Variation (%)") + ggtitle("Total CV") +
  theme_classic() + 
  theme(legend.position = "left") +
  geom_vline(xintercept = c(7.2), colour="black", linetype="dotted") +
  theme(plot.title = element_text(face = 'bold.italic', size = 12, hjust = 0)) + 
  theme(axis.text.x = element_text(angle = 60, vjust = 1.2, hjust = 1.3)) + #Set the text angle
  theme(panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  # Change axis line
  axis.line = element_line(colour = "black")); total.CV
```


Plot MAD
```{r}
## Resp 
resp.mad <- phys.mad %>% subset(Response == "Pnet_umol.cm2.hr" | Response == "Pgross_umol.cm2.hr" | Response == "Rdark_umol.cm2.hr") %>% na.omit()

Resp.MAD <- ggplot(resp.mad, aes(x=Timepoint, y = mad, group = Treatment, color = Treatment)) +
  geom_line() + geom_point() +
  facet_grid(Response ~ Species, scales = "free") +
  scale_color_manual(values = cols) + 
  xlab("Timepoint") + ylab("Median Absolute Deviation") + ggtitle("Resp / Photo MAD") +
  theme_classic() + 
  theme(legend.position = "left") +
  #geom_vline(xintercept = c(7.8), colour="black", linetype="dotted") +
  theme(plot.title = element_text(face = 'bold.italic', size = 12, hjust = 0)) + 
  theme(axis.text.x = element_text(angle = 60, vjust = 1.2, hjust = 1.3)) + #Set the text angle
  theme(panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  # Change axis line
  axis.line = element_line(colour = "black")); Resp.MAD

Resp.CV <- ggplot(resp.mad, aes(x=Timepoint, y = cv, group = Treatment, color = Treatment)) +
  geom_line() + geom_point() +
  facet_grid(Response ~ Species, scales = "free") +
  scale_color_manual(values = cols) + 
  xlab("Timepoint") + ylab("Coefficient of Variation (%)") + ggtitle("Resp / Photo CV") +
  theme_classic() + 
  theme(legend.position = "left") +
  #geom_vline(xintercept = c(7.8), colour="black", linetype="dotted") +
  theme(plot.title = element_text(face = 'bold.italic', size = 12, hjust = 0)) + 
  theme(axis.text.x = element_text(angle = 60, vjust = 1.2, hjust = 1.3)) + #Set the text angle
  theme(panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  # Change axis line
  axis.line = element_line(colour = "black")); Resp.CV
  
Resp <- arrangeGrob(Resp.MAD, Resp.CV, ncol=1)
ggsave(file="Output/Final_Figures/MAD-Resp.png", Resp, width = 11, height = 10, units = c("in"))
```

```{r}
## Chl
chl.mad <- phys.mad %>% subset(Response == "chlc2.ug.cm2") %>% na.omit()

CHLMAD <- ggplot(chl.mad, aes(x=Timepoint, y = mad, group = Treatment, color = Treatment)) +
  geom_line() + geom_point() +
  facet_grid(~ Species, scales = "free") +
  scale_color_manual(values = cols) + 
  xlab("Timepoint") + ylab("Median Absolute Deviation") + ggtitle("Chlorophyll c2 MAD") +
  theme_classic() + 
  theme(legend.position = "left") +
  geom_vline(xintercept = c(7.2), colour="black", linetype="dotted") +
  theme(plot.title = element_text(face = 'bold.italic', size = 12, hjust = 0)) + 
  theme(axis.text.x = element_text(angle = 60, vjust = 1.2, hjust = 1.3)) + #Set the text angle
  theme(panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black")); CHLMAD

ggsave(file="Output/Final_Figures/MAD-Chl.png", CHLMAD, width = 11, height = 6, units = c("in"))
```

```{r}
## TAC and Prot
Tac.prot.mad <- phys.mad %>% subset(Response == "cre.umol.mgprot" | Response == "prot_mg.cm2") %>% na.omit()

PROT.TAC.MAD <- ggplot(Tac.prot.mad, aes(x=Timepoint, y = mad, group = Treatment, color = Treatment)) +
  geom_line() + geom_point() +
  facet_grid(Response ~ Species, scales = "free") +
  scale_color_manual(values = cols) + 
  xlab("Timepoint") + ylab("Median Absolute Deviation") + ggtitle("TAC and Protein MAD") +
  theme_classic() + 
  theme(legend.position = "left") +
  geom_vline(xintercept = c(7.2), colour="black", linetype="dotted") +
  theme(plot.title = element_text(face = 'bold.italic', size = 12, hjust = 0)) + 
  theme(axis.text.x = element_text(angle = 60, vjust = 1.2, hjust = 1.3)) + #Set the text angle
  theme(panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black")); PROT.TAC.MAD

ggsave(file="Output/Final_Figures/MAD-Prot-TAC.png", PROT.TAC.MAD, width = 11, height = 6, units = c("in"))
```

AFDW
```{r}
## AFDW 
AFDW.mad <- phys.mad %>% subset(Response == "Host_AFDW.mg.cm2" | Response == "Sym_AFDW.mg.cm2" | Response == "Ratio_AFDW.mg.cm2") %>% na.omit()

AFDW.MAD <- ggplot(AFDW.mad, aes(x=Timepoint, y = mad, group = Treatment, color = Treatment)) +
  geom_line() + geom_point() +
  facet_grid(Response ~ Species, scales = "free") +
  scale_color_manual(values = cols) + 
  xlab("Timepoint") + ylab("Median Absolute Deviation") + ggtitle("Tissue Biomass MAD") +
  theme_classic() + 
  theme(legend.position = "left") +
  geom_vline(xintercept = c(7.2), colour="black", linetype="dotted") +
  theme(plot.title = element_text(face = 'bold.italic', size = 12, hjust = 0)) + 
  theme(axis.text.x = element_text(angle = 60, vjust = 1.2, hjust = 1.3)) + #Set the text angle
  theme(panel.border = element_blank(),
  panel.grid.major = element_blank(),
  panel.grid.minor = element_blank(),
  axis.line = element_line(colour = "black")); AFDW.MAD

ggsave(file="Output/Final_Figures/MAD-AFDW.png", AFDW.MAD, width = 11, height = 6, units = c("in"))
```


```{r}

```

